[project]
name = "chafa-yt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "textual>=6.11.0",
    "youtube-dl>=2021.12.17",
]
